name: rick_and_morty
description: Rick and Morty API Test
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.2.0
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  equatable: ^2.0.3
  dio_logger: ^4.0.8+8
  #  firebase_core: ^1.13.1
  #  firebase_messaging: ^11.2.11
  #  flutter_screenutil: ^5.3.1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  #  intl: ^0.17.0
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1


  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
#  flutter_gen_runner: ^4.1.6
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
